import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BookDemoModalProvider } from "@/components/BookDemoModalProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.3.2/css/flag-icons.min.css"
        />
      </head>
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <BookDemoModalProvider>
          <main className="flex-1">{children}</main>
        </BookDemoModalProvider>
      </body>
    </html>
  );
}
